name: Deploy Documentation
on:
  push:
    branches:
      - master
jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:

    - name: checkout-master
      uses: actions/checkout@master
      
    - name: deploy-vuepress
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: DamSenViet/acpatterns-js
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm i && npm i babylonjs babylonjs-loaders --no-save && npm run build:esm && npm run build:docs
        BUILD_DIR: docs/.vuepress/dist/