name: Deploy Vuepress
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: DamSenViet/acpatterns-js
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm i && npm run build:docs
        BUILD_DIR: docs/.vuepress/dist/